version: '3'

services:
  nemaki-couchdb:
    image: aegif/nemakicouch
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - ./nemaki-couchdb/local.ini:/opt/couchdb/etc/local.ini
  nemaki-ui:
    image: tomcat:9.0-jre8-alpine
    volumes:
      - ../war-files/ui.war:/usr/local/tomcat/webapps/ui.war
      - ./nemaki-ui/classes:/usr/local/tomcat/shared/classes
      - ./tomcat/bin/setenv.bat:/usr/local/tomcat/bin/setenv.bat
      - ./tomcat/bin/setenv.sh:/usr/local/tomcat/bin/setenv.sh
    ports:
      - 8080:8080

  nemaki-core:
    image: tomcat:9.0-jre8-alpine
    volumes:
      - ../war-files/core.war:/usr/local/tomcat/webapps/core.war
      - ./nemaki-core/classes:/usr/local/tomcat/shared/classes
      - ./tomcat/bin/setenv.bat:/usr/local/tomcat/bin/setenv.bat
      - ./tomcat/bin/setenv.sh:/usr/local/tomcat/bin/setenv.sh
    ports:
      - 8081:8080
      
  nemaki-solr:
    image: tomcat:9.0-jre8-alpine
    volumes:
      - ../war-files/solr.war:/usr/local/tomcat/webapps/solr.war
      - ./nemaki-solr/classes:/usr/local/tomcat/shared/classes
      - ./tomcat/bin/setenv.bat:/usr/local/tomcat/bin/setenv.bat
      - ./tomcat/bin/setenv.sh:/usr/local/tomcat/bin/setenv.sh
      - ./tomcat/conf/Catalina:/usr/local/tomcat/conf/Catalina
    ports:
      - 8082:8080