version: '3'

services:
  nemaki-couchdb:
    image: couchdb:latest
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - ./nemaki-couchdb/data
    #   - ./nemaki-couchdb/compose.ini:/opt/couchdb/etc/compose.ini
    tty: yes
  nemaki-ui:
    # image: kirillf/centos-tomcat:latest
    build: ./centos-tomcat9
    volumes:
      - ../war-files/ui.war:/opt/tomcat/webapps/ui.war
      - ./nemaki-ui/classes:/opt/tomcat/shared/classes
      - ./tomcat/bin/setenv.bat:/opt/tomcat/bin/setenv.bat
      - ./tomcat/bin/setenv.sh:/opt/tomcat/bin/setenv.sh
    ports:
      - 8080:8080
    tty: yes

  nemaki-core:
    # image: kirillf/centos-tomcat:latest
    build: ./centos-tomcat9
    volumes:
      - ../war-files/core.war:/opt/tomcat/webapps/core.war
      - ./nemaki-core/classes:/opt/tomcat/shared/classes
      - ./tomcat/bin/setenv.bat:/opt/tomcat/bin/setenv.bat
      - ./tomcat/bin/setenv.sh:/opt/tomcat/bin/setenv.sh
    ports:
      - 8081:8080
    tty: yes
      
  nemaki-solr:
    # image: kirillf/centos-tomcat:latest
    build: ./centos-tomcat9
    volumes:
      - ../war-files/solr.war:/opt/tomcat/webapps/solr.war
      - ./nemaki-solr/classes:/opt/tomcat/shared/classes
      - ./tomcat/bin/setenv.bat:/opt/tomcat/bin/setenv.bat
      - ./tomcat/bin/setenv.sh:/opt/tomcat/bin/setenv.sh
      - ./tomcat/conf/Catalina:/opt/tomcat/conf/Catalina
    ports:
      - 8082:8080
    tty: yes